### ISSUE TITLE
Have you seen rio?

### ISSUE THREAD

**Issue by leeper** [ryapric/readit#1]
Interesting package. Just wondering if you'd seen [rio](https://cran.r-project.org/web/packages/rio/index.html), which implements a pretty similar idea. Mostly just an FYI.

**Comment by ryapric** [comment]
Well that's... really frustrating! I had Googled around and not come across anything other than `reader`, which hadn't been updated in a year and which I couldn't find a Github page for.

`rio` looks much more comprehensive; great work! And thank you for sharing! If anything, I'll take this as a learning experience hahaha.
